### PR TITLE
Add PR Review checklist github action

### PR DESCRIPTION
**Pull request by gooliajulia**

### CODE REVIEW

**Comment by yeezick** [comment]
- [ ] dev has reviewed their own pr
- [ ] no merge conflicts
(more as they come to me)

**Comment by yeezick** [comment]
Note to self -> for reviewing, dev should post PR in discord, then Julia or I will assign a reviewer by creating a thread -> reviewer reviews then adds a comment to thread for opener

**Comment by yeezick** [comment]
@gooliajulia looks good enough to merge right now, lmk if any other thoughts

**Review by yeezick — APPROVED** [review]

**Comment by gooliajulia** [comment]
@yeezick sweet, this looks good to me, too. Not sure why but merging is blocked for me on this PR currently..

**Comment by yeezick** [comment]
It's cause you're also an editor on this PR, I'll ping Jason

**Review by jasonmar08 — APPROVED** [review]
Approved!

**Pull request merged**
