### PR TITLE
Feature/bc 375 enhance project configs

### PR DESCRIPTION
**Pull request by jasonmar08**
- Set up prettier to run with every commit by using a pre-commit hook and installing `prettier` and `pre-commit` as a dev dependency. Every contributor should run `npm install` to set up changes.

### CODE REVIEW

**Review by yeezick — APPROVED** [review]

**Review by yeezick — APPROVED** [review]

**Comment by Bestnogm1** [comment]
nice lets get this bread!!

**Review by Bestnogm1 — COMMENTED** [review]
nice let's get this bread!

**Review by Bestnogm1 — COMMENTED** [review]
LGTB let's get this bnread

**Review by Bestnogm1 — APPROVED** [review]
Nice

**Pull request merged**
